[package]
name = "eq_files"
version = "0.1.0"
authors = ["Anarelion <anarelion@gmail.com>"]
edition = "2021"

[dependencies]
bitbybit = "1.2"
bytes = "1.0"
compress = "0.2"
lazy_static = "1.4"
thiserror = "1.0"
tracing = "0.1"
